{"name": "Проверка попытки логина курьера без поля login", "status": "passed", "description": "Пытаемся залогиниться на аккаунт без поля Логин и получаем ошибку 400 и соответствующий текст ответа", "start": 1718876272285, "stop": 1718876272402, "uuid": "96e294f3-26d4-4e27-921e-97fa51ab659f", "historyId": "c9626acb2d8f298ffc51c9dc636b43e9", "testCaseId": "c9626acb2d8f298ffc51c9dc636b43e9", "fullName": "tests.test_courier_login.TestLoginCourier#test_not_login_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-02PLGO0"}, {"name": "thread", "value": "11616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}