{"name": "Проверка логина несуществующим курьером", "status": "passed", "description": "Пытаемся залогиниться несуществующим аккаунтом курьера, получаем ошибку 404 и соотвествующее сообщение", "start": 1718707861371, "stop": 1718707861513, "uuid": "1c30ddd7-5a90-428f-ab50-586b8fec48e0", "historyId": "59c1190257832c75b2535cb60e758ffd", "testCaseId": "59c1190257832c75b2535cb60e758ffd", "fullName": "tests.test_courier_login.TestLoginCourier#test_no_such_username_and_password", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-02PLGO0"}, {"name": "thread", "value": "9392-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}